server:
  port: 8761

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lisago
# Mybatis配置
mybatis:
  # 映射文件路径
  mapper-locations: classpath:mapper/*.xml,classpath*:mybatis/**/mapper/*.xml
  # 配置类型别名
  type-aliases-package: org.tsb.springboot.model
